# Generated by Django 5.0.7 on 2024-08-15 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskresult',
            name='assignments',
        ),
    ]
