# Generated by Django 5.0.7 on 2024-08-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0003_taskresult_assignments_assignmentgrade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentgrade',
            name='student',
        ),
        migrations.AlterField(
            model_name='taskresult',
            name='assignments',
            field=models.ManyToManyField(blank=True, related_name='task_results', to='task_app.assignmentgrade'),
        ),
    ]
