# Generated by Django 5.0.7 on 2024-08-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0004_remove_assignmentgrade_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskresult',
            name='assignments',
            field=models.ManyToManyField(blank=True, related_name='task_result_grades', to='task_app.assignmentgrade'),
        ),
    ]
